name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SDL
      uses: libsdl-org/setup-sdl@v1
      id: sdl
      with:
        install-linux-dependencies: true
        version: 2-latest
        version-sdl-image: 2-latest
      
    - uses: actions/checkout@v4

    - name: make
      run: make

    - name: make check
      run: make check

    - name: make distcheck
      run: make distcheck
